
DATOS_DE_SESION                                                               ID1        ID2      LMODE    REQUEST SQL_ID           WAIT_CLASS     EVENT                                                                                                                                                    
---------------------------------------------------------------------- ---------- ---------- ---------- ---------- ---------------- -------------- ------------------------------------                                                                                                                     
- Holder: Alter system kill session '1311,11653,@1' immediate;             131094    3599177          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2091,14439,@1' immediate;             131094    3599177          0          6 60f26d3jp8wha    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1809,40376,@1' immediate;             524293    5491175          6          0 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1825,5291,@2' immediate;              524293    5491175          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2125,39777,@2' immediate;             786453    4330991          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1341,41797,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1419,48396,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1424,41459,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1433,25550,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1439,19317,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1536,4274,@1' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1622,22756,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1738,7621,@1' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1805,28145,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1811,40097,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1324,40570,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1344,33905,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1347,34561,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1416,57781,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1449,8457,@2' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1635,63049,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1803,40381,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1835,28959,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1896,41068,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2032,52724,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2033,59304,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2174,49026,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2183,63130,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2199,26309,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2221,2405,@1' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2223,55848,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2225,32168,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2284,62504,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2304,21307,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1903,16466,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1909,22370,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1923,63936,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2101,9331,@2' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2107,62888,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2119,8732,@2' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2176,23407,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2216,9378,@2' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1260,6544,@2' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1221,9137,@2' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1328,7141,@1' immediate;              786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2221,52868,@2' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1164,41092,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1311,11653,@1' immediate;             786453    4330991          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1733,8975,@2' immediate;             1310730    5146816          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1364,32688,@1' immediate;            1310730    5146816          0          6 8pkcd9s630zbz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1997,27179,@1' immediate;            1310730    5146816          0          6 0ykkuv8tyr32c    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1610,26616,@1' immediate;            1310730    5146816          0          6 g5d4byjat6vhd    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1328,7141,@1' immediate;             1769486    5773547          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2095,23936,@2' immediate;            1769486    5773547          0          6 9x566tvu8basa    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2026,13597,@1' immediate;            2293776    6296578          6          0 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2297,6707,@1' immediate;             2293776    6296578          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2015,34667,@2' immediate;            2293776    6296578          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1164,41092,@1' immediate;            2490373    4144135          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1519,40540,@2' immediate;            2490373    4144135          0          6 f2tmcsx6zca4c    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2288,30756,@2' immediate;            2490373    4144135          0          6 1azz9m9zjqzpp    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1342,48631,@2' immediate;            2490373    4144135          0          6 dhb41n6bq9838    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1439,19317,@1' immediate;            3473416    1556153          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1252,9395,@2' immediate;             3473416    1556153          0          6 58dwvcak7r78d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1248,60958,@1' immediate;            3473416    1556153          0          6 gvfx6111txd8k    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1424,41459,@1' immediate;            3538953    2062090          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1554,16245,@2' immediate;            3538953    2062090          0          6 0p7wr73skznvx    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2199,26309,@1' immediate;            3801094    1063500          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1336,25976,@2' immediate;            3801094    1063500          0          6 34r7p40st48d3    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1715,34929,@1' immediate;            4718621     858315          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '869,58574,@2' immediate;             4718621     858315          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1511,13634,@2' immediate;            4718621     858315          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1824,37950,@2' immediate;            4718621     858315          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2221,52868,@2' immediate;            6291484    4362349          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1247,11935,@1' immediate;            6291484    4362349          0          6 f9qtaa2fn0jqb    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1351,35745,@1' immediate;            6291484    4362349          0          6 0srjw0h6utg9k    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1260,6544,@2' immediate;             6488090    2724301          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2122,58995,@1' immediate;            6488090    2724301          0          6 fpn4zcxawdw8r    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1712,18697,@2' immediate;            6488090    2724301          0          6 fpn4zcxawdw8r    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2212,39448,@1' immediate;            6488090    2724301          0          6 cbmnr3zsgwrs3    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1799,13544,@2' immediate;            6684682    2347740          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1352,38030,@2' immediate;            6684682    2347740          0          6 fvxwh09uzhsfy    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1347,34561,@2' immediate;            8192000    1260298          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1255,6216,@2' immediate;             8192000    1260298          0          6 131x74kyg0z18    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1231,6318,@2' immediate;             8323084    1622969          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '2004,28204,@1' immediate;            8323084    1622969          0          6 6q3x0md9aymnn    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1217,46313,@2' immediate;           10420233     695411          6          0 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1908,4323,@1' immediate;            10420233     695411          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1344,33905,@2' immediate;           10878986     447695          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1641,20803,@2' immediate;           10878986     447695          0          6 fuuryk31ajmnu    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1539,64876,@2' immediate;           10878986     447695          0          6 a1t3473mzh5mv    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1536,4274,@1' immediate;            12189723     572628          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1732,12072,@2' immediate;           12189723     572628          0          6 18qsxb1ru4f69    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '415,40703,@1' immediate;            12648481     340950          6          0 3gmv3c5bk8uw3    Cluster        gc transaction table                                                                                                                                     
\ Waiter: Alter system kill session '2018,41011,@2' immediate;           12648481     340950          0          6 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '28,16842,@2' immediate;             12648481     340950          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2026,13597,@1' immediate;           12648481     340950          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '322,58833,@2' immediate;            12648481     340950          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1809,40376,@1' immediate;           12648481     340950          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1217,46313,@2' immediate;           12648481     340950          0          6 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1170,24970,@2' immediate;           12648481     340950          0          6 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            

100 rows selected.

