
SPOO &&OWNER_DE_LA_TABLA.._CREACION_TABLA_EJECUCION_HISTORIFICACION.log

CREATE TABLE &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION
(
 EJECUTAR NUMBER(1) NOT NULL CHECK  (EJECUTAR in (0,1)),
 DIA NUMBER(1) NOT NULL CHECK  (DIA in (1,2,3,4,5,6,7)),
 NOTAS VARCHAR(30)
);

INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,1,'LUNES');
INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,2,'MARTES');
INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,3,'MIERCOLES');
INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,4,'JUEVES');
INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,5,'VIERNES');
INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,6,'SABADO');
INSERT INTO &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION VALUES (0,7,'DOMINGO');
COMMIT;

SELECT * FROM &&OWNER_DE_LA_TABLA..EJECUCION_HISTORIFICACION;
undef OWNER_DE_LA_TABLA
spoo off;

