SYS@PROBID2> @locks4kill.sql

DATOS_DE_SESION                                                               ID1        ID2      LMODE    REQUEST SQL_ID           WAIT_CLASS     EVENT                                                                                                                                                    
---------------------------------------------------------------------- ---------- ---------- ---------- ---------- ---------------- -------------- ------------------------------------                                                                                                                     
- Holder: Alter system kill session '1244,30486,@1' immediate;              65543    4122106          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2082,31489,@1' immediate;              65543    4122106          0          6 787tbvntbxf2d    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1311,11653,@1' immediate;             131094    3599177          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2091,14439,@1' immediate;             131094    3599177          0          6 60f26d3jp8wha    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1815,18404,@1' immediate;             196619    3520155          6          0 7ts26vzht2nz1    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1412,25774,@2' immediate;             196619    3520155          0          4 5950vkxdg77tr    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1809,40376,@1' immediate;             524293    5491175          6          0 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1825,5291,@2' immediate;              524293    5491175          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2192,23111,@2' immediate;             720899    4608558          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1637,32416,@2' immediate;             720899    4608558          0          6 cuaqbq8b7u4kp    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1219,32229,@1' immediate;            1703954    4925209          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1421,28277,@2' immediate;            1703954    4925209          0          6 fjxz6gzhhp2py    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1328,7141,@1' immediate;             1769486    5773547          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2095,23936,@2' immediate;            1769486    5773547          0          6 9x566tvu8basa    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2026,13597,@1' immediate;            2293776    6296578          6          0 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2015,34667,@2' immediate;            2293776    6296578          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1165,30772,@1' immediate;            2359297    4669388          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '2119,8732,@2' immediate;             2359297    4669388          0          6 365ppsd1z218r    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1164,41092,@1' immediate;            2490373    4144135          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1519,40540,@2' immediate;            2490373    4144135          0          6 f2tmcsx6zca4c    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1838,15884,@1' immediate;            2883599    2743860          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1815,18404,@1' immediate;            2883599    2743860          0          6 7ts26vzht2nz1    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1227,4294,@1' immediate;             3276805    2181192          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2025,39784,@2' immediate;            3276805    2181192          0          6 d31kz0f6u6x8w    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1439,19317,@1' immediate;            3473416    1556153          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1248,60958,@1' immediate;            3473416    1556153          0          6 gvfx6111txd8k    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1252,9395,@2' immediate;             3473416    1556153          0          6 58dwvcak7r78d    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1424,41459,@1' immediate;            3538953    2062090          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1554,16245,@2' immediate;            3538953    2062090          0          6 0p7wr73skznvx    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1333,37007,@1' immediate;            3670017    1308746          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '28,16842,@2' immediate;              3670017    1308746          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2026,13597,@1' immediate;            3670017    1308746          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1987,14390,@1' immediate;            3670017    1308746          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '322,58833,@2' immediate;             3670017    1308746          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1217,46313,@2' immediate;            3670017    1308746          0          6 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '415,40703,@1' immediate;             3670017    1308746          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1170,24970,@2' immediate;            3670017    1308746          0          6 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2199,26309,@1' immediate;            3801094    1063500          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1336,25976,@2' immediate;            3801094    1063500          0          6 34r7p40st48d3    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1987,14390,@1' immediate;            4259860     457965          6          0 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1511,13634,@2' immediate;            4259860     457965          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '869,58574,@2' immediate;             4259860     457965          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1824,37950,@2' immediate;            4259860     457965          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1715,34929,@1' immediate;            4259860     457965          0          6 bxmdbqunxnmbx    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1417,10342,@2' immediate;            5111826    2499962          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1609,2795,@2' immediate;             5111826    2499962          0          6 g4dk382vpn8sv    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1899,11532,@1' immediate;            5111826    2499962          0          6 639zb9vzfmp7x    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1422,11901,@1' immediate;            5111826    2499962          0          6 9h708cjgksk3j    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2221,52868,@2' immediate;            6291484    4362349          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1247,11935,@1' immediate;            6291484    4362349          0          6 f9qtaa2fn0jqb    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1351,35745,@1' immediate;            6291484    4362349          0          6 0srjw0h6utg9k    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1804,42039,@2' immediate;            6422535    2997558          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1647,23077,@1' immediate;            6422535    2997558          0          6 9u0r0tsx5ku2f    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1260,6544,@2' immediate;             6488090    2724301          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2212,39448,@1' immediate;            6488090    2724301          0          6 cbmnr3zsgwrs3    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2122,58995,@1' immediate;            6488090    2724301          0          6 fpn4zcxawdw8r    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1712,18697,@2' immediate;            6488090    2724301          0          6 fpn4zcxawdw8r    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1891,30568,@2' immediate;            7995419    3475238          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1617,32104,@1' immediate;            7995419    3475238          0          6 2av1phj20w8t2    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1347,34561,@2' immediate;            8192000    1260298          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1255,6216,@2' immediate;             8192000    1260298          0          6 131x74kyg0z18    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2188,6156,@2' immediate;             8323103    1623919          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1901,12250,@2' immediate;            8323103    1623919          0          6 c7kxc26dzqaxt    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2291,13371,@1' immediate;            8323103    1623919          0          6 7rt68s0ygh5tn    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1169,44386,@2' immediate;           10354702     923326          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1823,1263,@1' immediate;            10354702     923326          0          6 7gm8dk9d08xuj    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1217,46313,@2' immediate;           10420233     695411          6          0 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1908,4323,@1' immediate;            10420233     695411          0          4 f4nhc9afd4v2s    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1346,45890,@2' immediate;           10551312     903880          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1221,9137,@2' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1231,6318,@2' immediate;            10551312     903880          0          6 0x99j0ctpyrth    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1260,6544,@2' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1164,41092,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1227,4294,@1' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1244,30486,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1311,11653,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1324,40570,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1344,33905,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1347,34561,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1416,57781,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1423,38277,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1449,8457,@2' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1635,63049,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1328,7141,@1' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1419,48396,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1424,41459,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1433,25550,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1438,52845,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1439,19317,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1503,4553,@1' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1512,22826,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1536,4274,@1' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1546,37339,@1' immediate;           10551312     903880          0          6 9n8t48xx9zc73    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1622,22756,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1637,24890,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1903,16466,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1909,22370,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2005,50637,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2101,9331,@2' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2107,62888,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2125,39777,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2216,9378,@2' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2221,52868,@2' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1805,28145,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1816,63925,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1835,28959,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1896,19314,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2004,28204,@1' immediate;           10551312     903880          0          6 6q3x0md9aymnn    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2032,52724,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2033,59304,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2174,49026,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2183,63130,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2199,26309,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2221,2405,@1' immediate;            10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2223,55848,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2284,62504,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2304,21307,@1' immediate;           10551312     903880          0          6 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1648,42680,@2' immediate;           10682388     747482          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1834,37311,@1' immediate;           10682388     747482          0          6 dhw583m7kttu4    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1554,1363,@1' immediate;            10682388     747482          0          6 6rfhrdw2gk3dx    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1344,33905,@2' immediate;           10878986     447695          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1641,20803,@2' immediate;           10878986     447695          0          6 fuuryk31ajmnu    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '2094,61610,@2' immediate;           11534369     200583          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1997,27179,@1' immediate;           11534369     200583          0          6 0ykkuv8tyr32c    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1610,26616,@1' immediate;           11534369     200583          0          6 g5d4byjat6vhd    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1364,32688,@1' immediate;           11534369     200583          0          6 8pkcd9s630zbz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1324,29384,@1' immediate;           11534369     200583          0          6 6xr4vqj5s7ww0    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1733,8975,@2' immediate;            11534369     200583          0          6 fkzng0c8rp7kp    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1929,22708,@2' immediate;           11599889     194094          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1408,39915,@2' immediate;           11599889     194094          0          6 0vxu1dk8z38bv    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2007,44541,@1' immediate;           11599889     194094          0          6 actp2v2gq2brn    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1512,22826,@1' immediate;           12124163     419930          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2026,3849,@2' immediate;            12124163     419930          0          6 9h708cjgksk3j    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1536,4274,@1' immediate;            12189723     572628          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1732,12072,@2' immediate;           12189723     572628          0          6 18qsxb1ru4f69    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1602,59295,@1' immediate;           12320777     381931          6          0                  Idle           SQL*Net message from client                                                                                                                              
\ Waiter: Alter system kill session '1799,13544,@2' immediate;           12320777     381931          0          6 3h4czjpu9b73w    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '415,40703,@1' immediate;            12648481     340950          6          0 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2018,41011,@2' immediate;           12648481     340950          0          6 2r0cc0krs92hz    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1809,40376,@1' immediate;           12648481     340950          0          6 8b9mzqgkxmf1b    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1896,19314,@1' immediate;           12779520     704650          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1803,40381,@2' immediate;           12779520     704650          0          6 gthrpdxvhqqqh    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '1264,65069,@1' immediate;           12779520     704650          0          6 3d0dhx731vstc    Application    enq: TX - row lock contention                                                                                                                            
- Holder: Alter system kill session '1637,24890,@1' immediate;           13041697     840202          6          0 52fjbsttdtx0d    Application    enq: TX - row lock contention                                                                                                                            
\ Waiter: Alter system kill session '2116,28169,@1' immediate;           13041697     840202          0          6 d079hkmxagmjf    Application    enq: TX - row lock contention                                                                                                                            

145 rows selected.

SYS@PROBID2> spoo off
