-- ===============================================================
-- NAME: sentencia.sql
-- DESCRIPTION: 
-- USAGE: Execute
-- AUTHOR:
-- ---------------------------------------------------------------
SELECT ROWID,NLB_CODALM,NLB_CODCLI,NLB_ARTICU,NLB_VARIA1,NLB_VARIA2,NLB_VARLOG,NLB_ALBARA,NLB_PEDIDO,NLB_TIPPED,NLB_unicaj,NLB_FECLEC,NLB_NUMSER,NLB_SITLOG,NLB_CODMOV,NLB_LINPED,NLB_CODAGR
FROM NSERIE_LB WHERE NLB_CODALM = '56' AND NLB_CODCLI = '385' AND NLB_CODMOV IS NULL AND ( NLB_FECLEC <= '16-02-2018 00:00:00') AND ( NLB_FECLEC >= '01-02-2018 00:00:00') AND ( (NLB_TIPPED='RU' and nlb_sitlog='BT' AND NLB_ALBARA='111082' AND NLB_CODALM = '56' AND NLB_CODCLI = '385' ) OR ( EXISTS
(SELECT 'X' FROM CABEC_PEDVEN WHERE CPV_CLIENT ='385' AND CPV_ALMACE='56' AND TO_CHAR(CPV_PEDIDO) = NLB_PEDIDO AND NLB_DIVPED=CPV_DIVPED AND CPV_CLIENT=NLB_CODCLI AND CPV_ALMACE = NLB_CODALM AND CPV_EXPEDI IN
(SELECT ERU_NUMEXP FROM EXPEDICION_RUTA, RUTAS WHERE ERU_CODRUT = RUT_CODRUT AND ERU_CODEMP = RUT_CODEMP AND RUT_ALMACE = '56' AND RUT_CODRUT = '111082')) AND NLB_TIPPED='PS') OR ( EXISTS
(SELECT 'X'FROM CABEC_PEDCOM,EXPEDICION_RUTA WHERE CPC_CODCLI ='385' AND CPC_ALMACE='56' AND CPC_PEDIDO = NLB_PEDIDO AND CPC_CODCLI = NLB_CODCLI AND CPC_ALMACE= NLB_CODALM AND cpc_expedi = eru_numexp and ERU_CODRUT = '111082') AND NLB_TIPPED IN ('PE','IP','EB')) OR ( EXISTS
(SELECT 'X' FROM CABEC_DEVPED,EXPEDICION_RUTA WHERE CDP_CODCLI ='385' AND CDP_ALMACE='56' AND TO_CHAR(CDP_CODIGO) = NLB_PEDIDO AND CDP_CODCLI = NLB_CODCLI AND CDP_ALMACE= NLB_CODALM AND cdp_expedi = ERU_NUMEXP and ERU_CODRUT = '111082') AND NLB_TIPPED IN ('DE','DB'))) order by nlb_feclec;
