-- ===============================================================
-- NAME: ts20171010.sql
-- DESCRIPTION: Creates a bigfile tablespace with autoextend
-- USAGE: Execute
-- AUTHOR:
-- ---------------------------------------------------------------
CREATE BIGFILE TABLESPACE TRUCKLOAD_DAT DATAFILE 
  '+DATA_X2' SIZE 16384M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON; 

CREATE BIGFILE TABLESPACE TRUCKLOAD_IND DATAFILE 
  '+DATA_X2' SIZE 16384M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
